# Configurable variables
system_hostname: "xx.adaplo.io"
odoo_version: "17.0"
linux_username: "odoo17"
postgres_username: "odoo17"
db_password: "Od00786-"
odoo_port: "8069"
nginx_port: "8080"
pgadmin_port: "5050"
apache_https_port: "8443"
git_token: "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"
github_token_synch: "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"
GITHUB_USERNAME: "shazadw1"

