odoo_version: "17.0"
odoo_port: "8069"
pg_password: "Od00786-"
pgadmin_port: "5050"
apache_https_port: "8443"
git_token: "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"
github_token_synch: "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"
GITHUB_USERNAME: "shazadw1"
users:
  - "waseem"
  - "kal"
allowed_ips:
  - "95.149.154.194"
  - "82.23.184.194"
  - "86.31.225.220"
allowed_fqdns:
  - "sysop.adaplo.co.uk"
